framework:
  #translator:      { fallbacks: ["%locale%"] }
  secret: '%env(APP_SECRET)%'
  form:            ~
  validation: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale:  "%locale%"
  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    # With this config, PHP's native session handling is used
    handler_id: ~
    cookie_secure: auto
    cookie_samesite: lax
  fragments:       ~
  assets:
    version: 6
  php_errors:
    log: true
  #csrf_protection: true
  #http_method_override: true
  #esi: true
  #fragments: true

