jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        directories:
            Sara:
                namespace_prefix: "App"
                path: "%kernel.project_dir%/src/Serializer/Entity"
