sentry:
  dsn: '%env(SENTRY_DSN)%'
  options:
    environment: '%kernel.environment%'
    release: '1.0' #your app version
    excluded_exceptions: #exclude validation errors
      - App\Exception\UserNotFoundException
      - Symfony\Component\Security\Core\Exception\AccessDeniedException
